# Windows CI build via the Appveyor service

version: '{build}'

# Build worker image (VM template)
image: Visual Studio 2015

# branches to build
branches:
  only:
    - master  

# skip_non_tags: true

environment:
  matrix:
    - QTDIR: C:\Qt\5.12.6\mingw73_64
      cname: mingw
    #- QTDIR: C:\Qt\5.12.6\msvc2015_64
    #  cname: Win64-VS2015
    #  VSVER: 14.0
  
# build platform, i.e. x86, x64, Any CPU.
platform:
  - x64
  
# build Configuration, i.e. Debug, Release, etc.
configuration:
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %cname%==mingw set make=mingw32-make.exe
  - if %cname%==mingw g++ --version
  - if %cname%==mingw %make% --version
  - if not %cname%==mingw call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  - if not %cname%==mingw set make=nmake.exe
  - if not %cname%==mingw %make% /? > nul
  - set BIN=softprojector

before_build:
  - if %cname%==mingw set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\shared
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir %APPVEYOR_BUILD_FOLDER%-build
  - qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%
  
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%-build
  - '%make%'

after_build:
  - mkdir deploy
  - copy %APPVEYOR_BUILD_FOLDER%\win32_build\bin\%BIN%.exe deploy\%BIN%.exe
  - windeployqt --%CONFIGURATION% deploy\%BIN%.exe --verbose=2 --qmldir %QTDIR%\qml
  - cd deploy
  - 7z a -tzip %BIN%_%CONFIGURATION%.zip . -r
  - cd ..
  - copy %APPVEYOR_BUILD_FOLDER%-build\deploy\%BIN%_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\%BIN%_%CONFIGURATION%.zip

artifacts:
  - path: '%BIN%_%CONFIGURATION%.zip'
    name: '%BIN%-latest'
