sudo: false
language: cpp

branches:
  only:
  - master

env:
  global:
    - PRO=softProjector
    - BIN=SoftProjector

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: require
      addons:
        apt:
          sources:
            # Add ppa for gcc-7
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            # Set ppa to get a modern version of qt
            - sourceline: 'ppa:beineri/opt-qt-5.12.1-xenial'
          packages:
            - g++-7
            - git
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env:
        - MATRIX_EVAL="COMPILER=clang++"

install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    export QTV=qt512;
    sudo apt update -qq;
    echo "Install QT libraries";
    sudo apt install build-essential ${QTV}base 
    ${QTV}multimedia ${QTV}declarative 
    libgl1-mesa-dev libpulse-dev;
    export ARTIFACT="$BIN*.AppImage";
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    echo "Download last version of Qt with brew";
    brew update > /dev/null;
    brew install qt5;
    chmod -R 755 /usr/local/opt/qt5/*;
    export QTDIR="/usr/local/opt/qt5";
    export PATH="$QTDIR/bin:$PATH";
    export ARTIFACT="$BIN*.dmg";
  fi

script:
- eval "${MATRIX_EVAL}"
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    echo "Load qt env";
    source /opt/qt*/bin/qt*-env.sh;
    echo "Build project";
    mkdir build && cd build;
    qmake ../$PRO.pro;
    make -j8;
    echo "Create deploy folder";
    mkdir deploy;
    mv ../unix_build/bin/$BIN deploy/;
    cp ../.desktop deploy/;
    cp ../icons/softprojector.png deploy/;
    echo "Download and run linuxdeployqt";
    wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
    chmod a+x linuxdeployqt*.AppImage;
    unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
    ./linuxdeployqt*.AppImage deploy/.desktop -verbose=2 -appimage;
  fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    echo "Build project";
    mkdir build && cd build;
    qmake ../$PRO.pro;
    make -j8;
    echo "Run macdeployqt";
    macdeployqt ../mac_build/bin/$BIN.app -dmg -verbose=2;
  fi
  
# Builds for pull requests skip the deployment step altogether
deploy:
# Deploy configuration for "beta" releases
  - provider: releases
    token:
      secure: otEDOcTs/M60aRG/D/sB8aC9OEOuFZ/F15p200kFzMjKKGRaPqG00IvaP7PrkgSjacA+2Xa8BpdTPIRZOlVLZypJUbK00yv4t7ZXKiAJqtogxtjP+F1qV5NWIOQAzeEx5c6oJDSU8PJyn5sekBQYFaWeddd1B2/PnY0x0qsnn4aC0cY3QA5ENtOh8uaRgUl9tXZ06dOGpWkpWHI6CVuT68Hxxho3zZ51zVhdnBiOODlWO+/p40NawXz66KMjh5CwvIW1vG+JeNRgzyodFLZaW2lObHl/FCXesHKTaD9r+/nZg/AczLCNyi9CZ9Jy1KLARA2FrpqMwL6v6wCLGKSfM2ozeEG6Zixtnaih3j+IxdkwAAFoWf0OzwRx21FvG5mi7bnCwe15uVF1Grz0P6AsTKEFrB8s4fmNAD52Rzq7lVOcAQstfbitatU/Jfzi36nV7W+qsLTprjDA2jtaSlmXARfAOyYJYNMCfex8WtmZuwKjCPWp9jXXYH60vv7s1ftlr5+uhkuA3E5UHxPcjmS5nTvX5uDAEz/tzMmUwmpS3HkgYFDevk7fx6IKAhN8PEtY68bjrBmZRk9mH1auYTUKKiQJNmQs38bbmfgeqFpVfm6vFSNTGW7HowxTVRg6iNKvAiSiAz1IyzDngwUrQ95Qjn22A4dhh55miGPotCr8ZX0=
    name: "Latest"
    release_notes: "Beta release of SoftProjector"
    skip_cleanup: true
    file_glob: true
    file: 
        - "deploy/*.AppImage"
        - "../mac_build/bin/*.dmg*"
    overwrite: true
    draft: false
    prerelease: true

# Deploy configuration for "stable" releases
  - provider: releases
    token:
      secure: otEDOcTs/M60aRG/D/sB8aC9OEOuFZ/F15p200kFzMjKKGRaPqG00IvaP7PrkgSjacA+2Xa8BpdTPIRZOlVLZypJUbK00yv4t7ZXKiAJqtogxtjP+F1qV5NWIOQAzeEx5c6oJDSU8PJyn5sekBQYFaWeddd1B2/PnY0x0qsnn4aC0cY3QA5ENtOh8uaRgUl9tXZ06dOGpWkpWHI6CVuT68Hxxho3zZ51zVhdnBiOODlWO+/p40NawXz66KMjh5CwvIW1vG+JeNRgzyodFLZaW2lObHl/FCXesHKTaD9r+/nZg/AczLCNyi9CZ9Jy1KLARA2FrpqMwL6v6wCLGKSfM2ozeEG6Zixtnaih3j+IxdkwAAFoWf0OzwRx21FvG5mi7bnCwe15uVF1Grz0P6AsTKEFrB8s4fmNAD52Rzq7lVOcAQstfbitatU/Jfzi36nV7W+qsLTprjDA2jtaSlmXARfAOyYJYNMCfex8WtmZuwKjCPWp9jXXYH60vv7s1ftlr5+uhkuA3E5UHxPcjmS5nTvX5uDAEz/tzMmUwmpS3HkgYFDevk7fx6IKAhN8PEtY68bjrBmZRk9mH1auYTUKKiQJNmQs38bbmfgeqFpVfm6vFSNTGW7HowxTVRg6iNKvAiSiAz1IyzDngwUrQ95Qjn22A4dhh55miGPotCr8ZX0=
    skip_cleanup: true
    file_glob: true
    file: 
        - "deploy/*.AppImage"
        - "../mac_build/bin/*.dmg*"
    overwrite: true
    draft: false
    prerelease: false
    on:
      tags: true
      repo: stefslon/softprojector
      condition: $TRAVIS_TAG =~ ([0-9]|[1-9][0-9])(\.([0-9]|[1-9][0-9])){2}$    # regex to match semver naming convention for stable full releases

